name: APK Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.22.0'
      - run: flutter pub get
      - name: Verify Environment Variables
        run: |
          echo "API_URL is set to ${{ secrets.API_URL }}"
          echo "BASE_URL is set to $BASE_URL"
        env:
          BASE_URL: ${{ secrets.API_URL }}
      - name: Build APK
        env:
          BASE_URL: ${{ secrets.API_URL }}
        run: flutter build apk --dart-define=API_URL=$BASE_URL
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
